build:
	@go build -o bin/spherix

install-geoip2:
	@wget -P share/GeoIP https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.02.04/GeoLite2-ASN.mmdb
	@wget -P share/GeoIP https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.02.04/GeoLite2-City.mmdb
	@wget -P share/GeoIP https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.02.04/GeoLite2-Country.mmdb
