FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir pipenv==2022.1.8
COPY Pipfile ./
RUN pipenv install --skip-lock
COPY . .
EXPOSE 8005
CMD ["pipenv", "run", "uvicorn", "app.main:app", "--app-dir", "src", "--host", "0.0.0.0", "--port", "8005", "--reload"]


