cases = {
    "79208533738": [
        {
            "id": 260052054,
            "list__username": ["kovinevmv"],
            "link": "https://t.me/kovinevmv",
            "first_name": "Maxim",
            "last_name": "Kovynev",
            "has_photo": "Нет",
            "status": "Недавно",
            "emoji_status": "Нет",
            "premium": "Нет",
            "bot": "Нет",
            "verified": "Нет",
            "restricted": "Нет",
            "support": "Нет",
            "scam": "Нет",
            "fake": "Нет",
            "description": "Lead Developer i-sphere.ru | FullStack Developer rosbank.ru",
            "__image_url": None,
            "__photos": [],
        }
    ],
    "kovinevmv": [
        {
            "id": 260052054,
            "list__username": ["kovinevmv"],
            "link": "https://t.me/kovinevmv",
            "first_name": "Maxim",
            "last_name": "Kovynev",
            "has_photo": "Нет",
            "status": "Недавно",
            "emoji_status": "Нет",
            "premium": "Нет",
            "bot": "Нет",
            "verified": "Нет",
            "restricted": "Нет",
            "support": "Нет",
            "scam": "Нет",
            "fake": "Нет",
            "description": "Lead Developer i-sphere.ru | FullStack Developer rosbank.ru",
            "__photos": [],
        }
    ],
    "79913644101": [
        {
            "id": 689751895,
            "list__username": [],
            "link": None,
            "first_name": "Alexey",
            "last_name": None,
            "has_photo": "Нет",
            "status": "Не в сети с 2023-05-28 12:50:28+00:00",
            "emoji_status": "Нет",
            "premium": "Нет",
            "bot": "Нет",
            "verified": "Нет",
            "restricted": "Нет",
            "support": "Нет",
            "scam": "Нет",
            "fake": "Нет",
            "description": "CIO I-sphere.ru",
            "__photos": [],
        }
    ],
    "79519399901": [
        {
            "id": 6055202344,
            "list__username": ["avtoklimat59"],
            "link": "https://t.me/avtoklimat59",
            "first_name": "",
            "last_name": "Автоклимат",
            "has_photo": "Да",
            "status": "Не в сети с 2023-05-16 06:17:52+00:00",
            "emoji_status": "Нет",
            "premium": "Нет",
            "bot": "Нет",
            "verified": "Нет",
            "restricted": "Нет",
            "support": "Нет",
            "scam": "Нет",
            "fake": "Нет",
            "description": "Продажа, установка и ремонта отопителей, рефрижераторов.",
            "__image_url": None,
            "__photos": [],
            "list__image": [],
        }
    ],
    "79992295925": ["Results not found"],
}
