devices = [
    {
        "manufacturer": "Google",
        "models": ["Pixel XL", "Pixel 2XL", "Pixel 3XL", "Pixel 3aXL", "Pixel 4XL"],
    },
    {
        "manufacturer": "Xiaomi",
        "models": [
            "M2010J19SG",
            "POCO F1",
            "Redmi 9A",
            "Xiaomi Mi 4",
            "Redmi Note 10 pro",
            "Redmi Note 10",
            "Xiaomi Redmi 1S",
            "Xiaomi Mi 10T",
            "Xiaomi Redmi 6 Pro",
            "Xiaomi Redmi Y3",
            "Xiaomi Redmi 9 Prime",
            "Redmi Note 7",
        ],
    },
    {
        "manufacturer": "Vivo",
        "models": [
            "Vivo Y33s",
            "Vivo V21 5G",
            "Vivo Y20T",
            "Vivo Y73 2021",
            "Vivo X60",
            "Vivo X70 Pro 5G",
            "Vivo U3x",
            "Vivo V20 Pro",
            "Vivo Y21 2021",
            "Vivo Y53s",
            "Vivo S12 Pro",
            "Vivo V21e 5G",
        ],
    },
    {
        "manufacturer": "OnePlus",
        "models": [
            "OnePlus 2",
            "OnePlus X",
            "OnePlus 7",
            "OnePlus 7 Pro",
            "OnePlus Nord CE 5G",
            "OnePlus 9 Pro",
            "OnePlus 8T",
            "OnePlus 9",
            "OnePlus 7T",
            "OnePlus 6T",
            "OnePlus Nord 2",
            "OnePlus Nord",
        ],
    },
    {
        "manufacturer": "Realme",
        "models": [
            "RMX2185",
            "Realme GT Neo2 5G",
            "Realme 8 5G",
            "Realme C11 2021",
            "Realme GT",
            "Realme Narzo 30",
            "Realme Q3i 5G",
            "Realme 8s 5G",
            "Realme 8i",
            "Realme Narzo 50A",
            "Realme C21Y",
        ],
    },
    {
        "manufacturer": "Oppo",
        "models": [
            "OPPO A55",
            "OPPO A74 5G",
            "OPPO A53",
            "OPPO A31",
            "OPPO A12",
            "OPPO Reno6 Pro",
            "OPPO Reno6",
            "OPPO F19 Pro",
            "OPPO F19s",
            "Oppo F19 Pro+",
            "Oppo A33",
            "Oppo Reno 3 Pro",
            "Oppo Reno 4 Pro",
            "Oppo Find X2",
            "OPPO F15",
            "OPPO Reno 2F",
            "OPPO K3",
            "OPPO A9",
            "OPPO A1k",
            "OPPO A5s",
        ],
    },
    {
        "manufacturer": "Samsung",
        "models": [
            "Samsung Galaxy M31s",
            "Samsung Galaxy M32",
            "Samsung Galaxy F62",
            "Samsung Galaxy M52 5G",
            "Samsung Galaxy M12",
            "Samsung Galaxy M51",
            "Samsung Galaxy F12",
            "Samsung Galaxy F22",
            "Samsung Galaxy A52",
            "Samsung Galaxy S20 FE 5G",
            "Samsung Galaxy M52",
            "Samsung Galaxy M62",
            "Samsung Galaxy S21 Ultra",
            "Samsung Galaxy A52s 5G",
            "Samsung Galaxy S21",
            "Samsung Galaxy M21 2021",
            "Samsung Galaxy F42",
            "Samsung Galaxy A12",
            "Samsung Galaxy F41",
            "Samsung Galaxy M01 Core",
        ],
    },
]
