FROM python:3.11

RUN apt-get update && \
    apt-get install --no-install-recommends -y ffmpeg=7:5.1.5-0+deb12u1 libsm6=2:1.2.3-1 libxext6=2:1.3.4-1+b1 tesseract-ocr=5.3.0-2 tesseract-ocr-eng=1:4.1.0-2 tesseract-ocr-rus=1:4.1.0-2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*