FROM python:3.11-slim-buster

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y wget=1.20.1-1.1 gnupg=2.2.12-1+deb10u2 && \
    mkdir /etc/apt/keyrings && \
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null && \
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null  && \
    echo 'Package: * Pin: origin packages.mozilla.org Pin-Priority: 1000 ' | tee /etc/apt/preferences.d/mozilla  && \
    apt-get update && apt-get install --no-install-recommends -y firefox && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
