from src.utils.env import parse_dotenv

_PROXY_LOGIN, _PROXY_PASSWORD, _SELENIUM_BROWSER_DRIVER_PATH, _RU_CAPTCHA, _LOG_LEVEL, _MONGO_HOST, _MONGO_PORT, \
_MONGO_DB, _MONGO_COLLECTION, _MONGO_SERVICE = parse_dotenv()

SELENIUM_BROWSER_DRIVER_PATH = _SELENIUM_BROWSER_DRIVER_PATH
RU_CAPTCHA = _RU_CAPTCHA
LOG_LEVEL = _LOG_LEVEL

MONGO_HOST = _MONGO_HOST
MONGO_PORT = _MONGO_PORT
MONGO_DB = _MONGO_DB
MONGO_COLLECTION = _MONGO_COLLECTION
MONGO_SERVICE = _MONGO_SERVICE
