"""

Revision ID: e4f5f900c877
Revises: 4de7dcd68504
Create Date: 2023-11-27 06:28:07.164436

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "e4f5f900c877"
down_revision: Union[str, None] = "4de7dcd68504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "captcha_task", sa.Column("solution", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "source",
        sa.Column(
            "solution_specification",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "solution_specification")
    op.drop_column("captcha_task", "solution")
    # ### end Alembic commands ###
