"""empty message

Revision ID: da62f1555e03
Revises: 86600843b4ae
Create Date: 2024-04-18 11:31:05.888990

"""

import json
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]
from src.logic.source import captcha_source_service

# revision identifiers, used by Alembic.
revision: str = "da62f1555e03"
down_revision: Union[str, None] = "86600843b4ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source",
        sa.Column(
            "auto_mode_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                f"'{json.dumps(captcha_source_service.repository.model.default_auto_mode_config)}'"
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "source",
        "solution_specification",
        server_default=sa.text(
            f"'{json.dumps(captcha_source_service.repository.model.default_solution_specification)}'"
        ),
        existing_nullable=True,
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "auto_mode_config")
    op.alter_column(
        "source",
        "solution_specification",
        server_default=None,
        existing_nullable=False,
        nullable=True,
    )
    # ### end Alembic commands ###
