"""empty message

Revision ID: 86600843b4ae
Revises: 8e495423137c
Create Date: 2024-03-11 08:33:24.975970

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]
from src.common import enums

# revision identifiers, used by Alembic.
revision: str = "86600843b4ae"
down_revision: Union[str, None] = "8e495423137c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("captcha_task", "image_task")
    op.execute("ALTER SEQUENCE captcha_task_id_seq RENAME TO image_task_id_seq")
    op.execute("ALTER INDEX captcha_task_pkey RENAME TO image_task_pkey")

    op.create_table(
        "website",
        sa.Column("url", sa.String(2048), nullable=False),
        sa.Column("name", sa.String(50), nullable=False, unique=True),
        sa.Column("max_token_pool", sa.SmallInteger(), nullable=False),
        sa.Column("min_token_pool", sa.SmallInteger(), nullable=False),
        sa.Column("current_token_pool", sa.SmallInteger(), nullable=False),
        sa.Column(
            "website_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_task",
        sa.Column("solution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("website", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=True),
        sa.Column("decode_time", sa.REAL(precision=6), nullable=True),
        sa.Column("status", enums.task_status_enum_postgresql, nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["website"], ["website.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_task")
    op.drop_table("website")

    op.rename_table("image_task", "captcha_task")
    op.execute("ALTER SEQUENCE image_task_id_seq RENAME TO captcha_task_id_seq")
    op.execute("ALTER INDEX image_task_pkey RENAME TO captcha_task_pkey")
    # ### end Alembic commands ###
