"""empty message

Revision ID: 5d629272be15
Revises: e4f5f900c877
Create Date: 2024-01-21 12:01:04.173431

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "5d629272be15"
down_revision: Union[str, None] = "74d489a3d33e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "captcha_task", sa.Column("s3_filename", sa.String(length=120), nullable=True)
    )
    op.alter_column(
        "captcha_task",
        "solution",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=65),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("captcha_task", "s3_filename")
    op.alter_column(
        "captcha_task",
        "solution",
        existing_type=sa.String(length=65),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
