from src.utils.env import parse_dotenv

_PROXY_LOGIN, _PROXY_PASSWORD, _KEYDB_HOST, _KEYDB_PASSWORD, _MONGO_SERVER, _MONGO_PORT, _MONGO_DB, _MONGO_COLLECTION = parse_dotenv(
)

PROXY_LOGIN = _PROXY_LOGIN
PROXY_PASSWORD = _PROXY_PASSWORD

KEYDB_HOST = _KEYDB_HOST
KEYDB_PASSWORD = _KEYDB_PASSWORD

MONGO_SERVER = _MONGO_SERVER
MONGO_PORT = _MONGO_PORT
MONGO_DB = _MONGO_DB
MONGO_COLLECTION = _MONGO_COLLECTION
