cases = {
    "+79208313140": [
        {
            "_id": "1105603434",
            "url_yandex": "https://yandex.ru/maps/191/bryansk/category/audio_and_video_devices_repair/184108221/",
            "name": "Радиоцех",
            "short_title": None,
            "description": None,
            "country": "Россия",
            "city": "Брянск",
            "address": "просп. Ленина, 67, Брянск",
            "address_comment": "офис 236б, этаж 2",
            "full_address": "Брянск, проспект Ленина, 67",
            "post_code": "241050",
            "coordinates": [53.250662, 34.371287],
            "list__categories": [
                "Ремонт аудиотехники и видеотехники",
                "Ремонт бытовой техники",
            ],
            "list__seoname": [
                "radiotsekh",
                "audio_and_video_devices_repair",
                "appliance_repair",
            ],
            "abilities": None,
            "type": "business",
            "schedule": "пн-пт 10:00–18:00; сб 11:00–17:00",
            "list__phone": ["+79208313140", "+79103331101"],
            "list__url": [],
            "panorama": "https://static-pano.maps.yandex.ru/v1/?panoid=1278770310_698887627_23_1594977067&size=500%2C240&azimuth=127.5&tilt=10&api_key=maps&signature=NQoB_9CoDVi9vWc1s077u3eghXWeIOXb-o9ejMBO8XQ=",
            "list__images": [
                "https://avatars.mds.yandex.net/get-altay/2383444/2a0000017466d3ddc55f89cf810518f15ac4/XXXL",
                "https://avatars.mds.yandex.net/get-altay/5265775/2a0000017be2aeb5200f62094e2334b2fd0f/XXXL",
                "https://avatars.mds.yandex.net/get-altay/1042100/2a00000168d47e8cff316f5f463905a5f10e/XXXL",
                "https://avatars.mds.yandex.net/get-altay/5254019/2a0000017be2aec5942d1d20de0857aa2756/XXXL",
            ],
            "count_images": 4,
            "rating_general": 0,
            "rating_count": 0,
            "review_count": 1,
            "neuro_review": None,
            "aspects": None,
            "stops": '"Площадь Революции" (158 м);\n"Гостиница Брянск" (550 м);\n"Покровская гора" (800 м);\n"Драмтеатр" (1,29 км);\n"Набережная" (1,37 км);',
            "metro": None,
            "load": None,
            "has_verified_owner": "Нет",
            "has_stories": "Нет",
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        }
    ],
    "+78005009977%20Брянск": [
        {
            "_id": "53057293",
            "url_yandex": "https://yandex.ru/maps/geo/bryansk/53057293/",
            "name": "Брянск",
            "short_title": None,
            "description": "",
            "country": "Россия",
            "city": "Брянск",
            "address": "Брянск",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [53.2434, 34.363991],
            "list__categories": [],
            "list__seoname": ["bryansk"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": "https://static-pano.maps.yandex.ru/v1/?panoid=1278730257_698962293_23_1594012333&size=500%2C240&azimuth=136.11330179707147&tilt=1&api_key=maps&signature=7ywsn0F4sePRWnfKxwwTnjhi-BWxa2U0GsH3BzCYTTQ=",
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=sdPhh89oynig_N9RhRcOTQ&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=v741wo_pwRTE83BwJo9-pA&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=-t-xRSxTf4Mf7G1tSHbpRA&image_size=XXXL",
            ],
            "count_images": 30,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "53107282",
            "url_yandex": "https://yandex.ru/maps/geo/selo_bryansk/53107282/",
            "name": "село Брянск",
            "short_title": None,
            "description": "Кабанский район, Республика Бурятия",
            "country": "Россия",
            "city": "Республика Бурятия",
            "address": "Республика Бурятия, Кабанский район, село Брянск",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [52.033552, 106.867961],
            "list__categories": [],
            "list__seoname": ["selo_bryansk"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=VDxldvla7FZrL_JUXe0bxw&image_size=XXXL"
            ],
            "count_images": 1,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "53121359",
            "url_yandex": "https://yandex.ru/maps/geo/selo_bryansk/53121359/",
            "name": "село Брянск",
            "short_title": None,
            "description": "Кизлярский район, Республика Дагестан",
            "country": "Россия",
            "city": "Республика Дагестан",
            "address": "Республика Дагестан, Кизлярский район, село Брянск",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [44.330058, 46.982815],
            "list__categories": [],
            "list__seoname": ["selo_bryansk"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [],
            "count_images": None,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "1508541221",
            "url_yandex": "https://yandex.ru/maps/geo/1508541221/",
            "name": "деревня Брянск",
            "short_title": None,
            "description": "Ботвиновский сельсовет, Кричевский район, Могилёвская область",
            "country": "Беларусь",
            "city": "Могилёвская область",
            "address": "Могилёвская область, Кричевский район, Ботвиновский сельсовет, деревня Брянск",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [53.748907, 31.545779],
            "list__categories": [],
            "list__seoname": [],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [],
            "count_images": None,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "4505095250",
            "url_yandex": "https://yandex.ru/maps/10650/bryansk-oblast/geo/gorodok_bryansk_18/4505095250/",
            "name": "городок Брянск-18",
            "short_title": None,
            "description": "Жуковский муниципальный округ, Брянская область",
            "country": "Россия",
            "city": "Брянская область",
            "address": "Брянская область, Жуковский муниципальный округ, городок Брянск-18",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [53.496192, 33.87511],
            "list__categories": [],
            "list__seoname": ["gorodok_bryansk_18"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [],
            "count_images": None,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "1489606200",
            "url_yandex": "https://yandex.ru/maps/geo/aeroport_bryansk/1489606200/",
            "name": "аэропорт Брянск",
            "short_title": None,
            "description": "Брянский район",
            "country": "Россия",
            "city": "Брянская область",
            "address": "Брянский район, аэропорт Брянск",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [53.213493, 34.18272],
            "list__categories": [],
            "list__seoname": ["aeroport_bryansk"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=6yvy7ZeTgxLP1kysdy-65w&image_size=XXXL"
            ],
            "count_images": 1,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "8000017",
            "url_yandex": "https://yandex.ru/maps/225/russia/geo/m_3_ukraina/8000017/",
            "name": "М-3 Украина",
            "short_title": None,
            "description": "",
            "country": "Россия",
            "city": "Россия",
            "address": "М-3 Украина",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [54.107448, 35.244933],
            "list__categories": [],
            "list__seoname": ["m_3_ukraina"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=NUxgo8ub4y2JFw002bN&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=MmyiJRFSXYTf5eFo1Yh&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=QuU9Fsi3Ir6VTvpQfA1QZw&image_size=XXXL",
            ],
            "count_images": 30,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "1487996097",
            "url_yandex": "https://yandex.ru/maps/geo/briansk_konotop/1487996097/",
            "name": "Брянск – Конотоп",
            "short_title": None,
            "description": "Сумская область",
            "country": "Украина",
            "city": "Сумская область",
            "address": "Сумская область, Брянск – Конотоп",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [51.797083, 33.537415],
            "list__categories": [],
            "list__seoname": ["briansk_konotop"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=zX05A55Dxr7ZVzn5CDDm_A&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=NmXr5nw1EAgeY1bcG7gLMw&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=gFX1bBbyebd6dp4NWu1eUA&image_size=XXXL",
            ],
            "count_images": 3,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "1729410181",
            "url_yandex": "https://yandex.ru/maps/geo/bryansk_lgovskiy_oryol/1729410181/",
            "name": "Брянск-Льговский - Орёл",
            "short_title": None,
            "description": "",
            "country": "Россия",
            "city": "Центральный федеральный округ",
            "address": "Брянск-Льговский - Орёл",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [53.123604, 35.280057],
            "list__categories": [],
            "list__seoname": ["bryansk_lgovskiy_oryol"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=cM2w6KGJ8AcBfw2Ser2ncA&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=ZZwMICH62WeqFabS6rDbsw&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=PbGgiv0D1FNGMCFsjI6&image_size=XXXL",
            ],
            "count_images": 9,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
        {
            "_id": "8021037",
            "url_yandex": "https://yandex.ru/maps/225/russia/geo/a_240/8021037/",
            "name": "А-240",
            "short_title": None,
            "description": "",
            "country": "Россия",
            "city": "Россия",
            "address": "А-240",
            "address_comment": None,
            "full_address": None,
            "post_code": "",
            "coordinates": [52.791906, 32.970147],
            "list__categories": [],
            "list__seoname": ["a_240"],
            "abilities": None,
            "type": "toponym",
            "schedule": None,
            "list__phone": [],
            "list__url": [],
            "panorama": None,
            "list__images": [
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=i1xeWH0CcdT_IaIkzxiwhw&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=X4Nc17n2BHGtWBYeUGgfng&image_size=XXXL",
                "https://core-pht-proxy.maps.yandex.ru/v1/photos/download?photo_id=qcZ2dDnxSRsfUkMy5_hNHQ&image_size=XXXL",
            ],
            "count_images": 29,
            "rating_general": 0,
            "rating_count": None,
            "review_count": None,
            "neuro_review": None,
            "aspects": None,
            "stops": None,
            "metro": None,
            "load": None,
            "has_verified_owner": None,
            "has_stories": None,
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        },
    ],
    "sadik32.vov.ru": [
        {
            "_id": "1000573192",
            "url_yandex": "https://yandex.ru/maps/191/bryansk/category/kindergarten_nursery/184107206/",
            "name": "Детский сад № 64 Веселая семейка",
            "short_title": "Детский сад № 64 Весёлая семейка",
            "description": None,
            "country": "Россия",
            "city": "Брянск",
            "address": "пер. Чернышевского, 12, Брянск",
            "address_comment": None,
            "full_address": "Брянск, переулок Чернышевского, 12",
            "post_code": "241047",
            "coordinates": [53.254685, 34.451925],
            "list__categories": ["Детский сад, ясли", "Дополнительное образование"],
            "list__seoname": [
                "detskiy_sad_64_veselaya_semeyka",
                "kindergarten_nursery",
                "further_education",
            ],
            "abilities": None,
            "type": "business",
            "schedule": "пн-пт 07:00–19:00",
            "list__phone": ["+74832732697"],
            "list__url": ["http://sadik32.vov.ru/"],
            "panorama": "https://static-pano.maps.yandex.ru/v1/?panoid=1279258570_698850850_23_1593863559&size=500%2C240&azimuth=-89.9&tilt=10&api_key=maps&signature=Zv52St_2HACQLHQWqdJj5FaF6BRH1J9Ae9oVSH4kYrM=",
            "list__images": [
                "https://avatars.mds.yandex.net/get-altay/4524003/2a0000017b8616d66b421ba1b9e7f9f5a5c2/XXXL",
                "https://avatars.mds.yandex.net/get-altay/225456/2a0000015ff7ad4ed7c332da0d268864d68a/XXXL",
            ],
            "count_images": 2,
            "rating_general": 4.5,
            "rating_count": 81,
            "review_count": 18,
            "neuro_review": None,
            "aspects": None,
            "stops": '"Сосновый Бор" (350 м);\n"Улица Тельмана" (350 м);\n"Улица Рылеева" (520 м);\n"Магазин" (830 м);\n"Полпинская" (1,03 км);',
            "metro": None,
            "load": None,
            "has_verified_owner": "Нет",
            "has_stories": "Нет",
            "business_images": None,
            "has_commercial": None,
            "commercial_article": None,
            "commercial_text": None,
            "commercial_logo": None,
            "commercial_url": None,
            "commercial_banner": None,
        }
    ],
}
