cs-fix:
	@find . -type f -name "*.php" -maxdepth 1 -exec php-cs-fixer fix {} \;
	@php-cs-fixer fix bin/
	@php-cs-fixer fix bulkAuto/
	@php-cs-fixer fix engine/
	@php-cs-fixer fix public/
	@php-cs-fixer fix rules/
	@php-cs-fixer fix src/
