cases = {
    "+78005553535": [
        {
            "name": "домашние деньги",
            "description": "I’m 20",
            "user_definition": None,
            "avatar": "https://lh3.googleusercontent.com/p/AF1QipMnRvyN0OnHOY4aNpvbFq8ydLBkCiqi2ghnqBYi=k",
            "is_own_photo": None,
            "birthday": None,
            "list__email": None,
            "facebook": "https://facebook.com/208295989767031",
            "twitter": "https://twitter.com/KrabLoveNBOMe",
            "vkontakte": "https://vk.com/id509273374",
            "linkedin": None,
            "foursquare": None,
            "pinterest": None,
            "instagram_id": None,
            "list__website": ["http://www.doorcenter.spb.ru/"],
            "list__address": [
                "ул. Красная, 186, Краснодар, Краснодарский край, Россия, 350020",
                "Tselinograd, Kazakhstan",
            ],
            "google_maps": "https://www.google.com/maps/place/?q=place_id:ChIJc0NFUoNP8EARV6r0qnyGBDY",
            "coordinates": [45.04900349999999, 38.979979],
            "schedule": "Пн: 08:30 - 17:00,\nВт: 08:30 - 17:00,\nСр: 08:30 - 17:00,\nЧт: 08:30 - 17:00,\nПт: 08:30 - 17:00,\nСб: -,\nВс: -",
            "categories": "Personal Blog",
            "reviews": "не отвечают",
            "rating": 3.4,
            "is_spam": "Да",
            "price_level": None,
            "is_install_app": "Нет",
            "active_during_period": "Нет",
            "priority": 167,
        }
    ],
    "+79039687447": [
        {
            "name": "Андрей Виноградов",
            "description": None,
            "user_definition": None,
            "avatar": None,
            "is_own_photo": None,
            "birthday": None,
            "list__email": ["anvin.ru@gmail.com"],
            "facebook": None,
            "twitter": None,
            "vkontakte": None,
            "linkedin": None,
            "foursquare": None,
            "pinterest": None,
            "instagram_id": None,
            "list__website": [],
            "list__address": [],
            "google_maps": None,
            "coordinates": None,
            "schedule": None,
            "categories": None,
            "reviews": None,
            "rating": None,
            "is_spam": "Нет",
            "price_level": None,
            "is_install_app": "Да",
            "active_during_period": "Нет",
            "priority": 100,
        }
    ],
    "+79208313140": [
        {
            "name": "владимир",
            "description": None,
            "user_definition": None,
            "avatar": None,
            "is_own_photo": None,
            "birthday": None,
            "list__email": None,
            "facebook": None,
            "twitter": None,
            "vkontakte": None,
            "linkedin": None,
            "foursquare": None,
            "pinterest": None,
            "instagram_id": None,
            "list__website": [
                "https://plus.google.com/118051206674965050989/about?hl=en"
            ],
            "list__address": ["67 prospekt Lenina, Bryansk, Брянск, Russia, 241050"],
            "google_maps": None,
            "coordinates": [53.250606, 34.37147600000003],
            "schedule": None,
            "categories": None,
            "reviews": None,
            "rating": None,
            "is_spam": "Нет",
            "price_level": None,
            "is_install_app": "Нет",
            "active_during_period": "Нет",
            "priority": 56,
        }
    ],
    "79208313141": "NoDataEvent(SCS-204) - User not found",
    "79377097001": [
        {
            "name": "Дмитрий Сергеев",
            "description": None,
            "user_definition": None,
            "avatar": "https://s3.amazonaws.com/callapp-profile-pictures/212d5917-4727-419c-bdb6-dcd0051cbf82",
            "is_own_photo": "Да",
            "birthday": "23.05.1994",
            "list__email": ["grizzly9405@gmail.com"],
            "facebook": None,
            "twitter": None,
            "vkontakte": None,
            "linkedin": None,
            "foursquare": None,
            "pinterest": None,
            "instagram_id": None,
            "list__website": [],
            "list__address": [],
            "google_maps": None,
            "coordinates": None,
            "schedule": None,
            "categories": None,
            "reviews": None,
            "rating": None,
            "is_spam": "Нет",
            "price_level": None,
            "is_install_app": "Да",
            "active_during_period": "Да",
            "priority": 100,
        }
    ],
}
