cases = {
    "+79208533738": {
        "Name": "Maxim Kovynev",
        "avatar": None,
        "alternative_name": None,
        "phone_number_type": "Мобильный",
        "country_code": "RU",
        "phone_number_operator": "MegaFon",
        "list__extra_phone": [],
        "badges": "user",
        "score": 0.9,
        "is_install_app": "Да",
        "gender": "Неизвестно",
        "about": "",
        "birthday": None,
        "job_title": "",
        "company": "",
        "search_warnings": "",
        "list__address": [],
        "tags": "",
        "spam_score": None,
        "spam_category": None,
        "comments_count": None,
        "comments_exists": "Нет",
    },
    "78005557778": {
        "Name": "Тинькофф - Банк",
        "avatar": None,
        "alternative_name": None,
        "phone_number_type": "Бесплатная (горячая) линия",
        "country_code": "RU",
        "phone_number_operator": "Multiple Providers",
        "list__extra_phone": [],
        "badges": "",
        "score": 0.8,
        "is_install_app": "Нет",
        "gender": "Неизвестно",
        "about": None,
        "birthday": None,
        "job_title": None,
        "company": None,
        "search_warnings": "",
        "list__address": [],
        "tags": "Finance & Insurance\n",
        "spam_score": 456,
        "spam_category": "TOP_SPAMMER",
        "comments_count": 14,
        "comments_exists": "Да",
    },
    "77786401814": {
        "Name": "John Maximov",
        "avatar": "https://images-noneu.truecallerstatic.com/myview/1/73ba398ff734e84c1c95588100d00eb5/1",
        "alternative_name": None,
        "phone_number_type": "Мобильный",
        "country_code": "KZ",
        "phone_number_operator": "Kcell",
        "list__extra_phone": [],
        "badges": "user",
        "score": 0.9,
        "is_install_app": "Да",
        "gender": "Мужской",
        "about": "54646",
        "birthday": "2002-01-22",
        "job_title": "2",
        "company": "1",
        "search_warnings": "",
        "list__address": ["KZ, 112313, Jump"],
        "list__email": ["fsdgdsfgdfg@gsdf.cob"],
        "list__link": ["https://vk.com"],
        "tags": "",
        "spam_score": None,
        "spam_category": None,
        "comments_count": None,
        "comments_exists": "Нет",
    },
}
