FROM git.i-sphere.local/isphere-images/python:3.11-alpine
WORKDIR /app
ARG GIT_HTTP_URL_WITH_CREDENTIALS
ENV TZ="Europe/Moscow"
COPY cleaner/Pipfile .
RUN pip install --no-cache-dir pipenv==2022.1.8 && \
    pipenv install --skip-lock --system --deploy && \
    pip uninstall pipenv -y
COPY src /app/src
COPY cleaner /app/cleaner
ENV PYTHONPATH "${PYTHONPATH}:/cleaner"
RUN chmod +x /app/cleaner/start.sh
CMD [ "./cleaner/start.sh" ]
