FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY Pipfile ./
RUN pip install --no-cache-dir pipenv==2022.1.8 && \
    pipenv install --skip-lock --system --deploy && \
    pip uninstall pipenv -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY . .
RUN chmod +x ./start.sh
EXPOSE 8005
CMD ["./start.sh"]


