from src.utils.env import parse_dotenv

_PROXY_LOGIN, _PROXY_PASSWORD, _KEYDB_HOST, _KEYDB_PASSWORD, _WITH_GENERATION_TOKEN, _MONGO_TOKEN_DB, _MONGO_TOKEN_PORT = parse_dotenv(
)

PROXY_LOGIN = _PROXY_LOGIN
PROXY_PASSWORD = _PROXY_PASSWORD

KEYDB_HOST = _KEYDB_HOST
KEYDB_PASSWORD = _KEYDB_PASSWORD

WITH_GENERATION_TOKEN = _WITH_GENERATION_TOKEN
MONGO_TOKEN_DB = _MONGO_TOKEN_DB
MONGO_TOKEN_PORT = _MONGO_TOKEN_PORT
