from src.utils.env import parse_dotenv

_MONGO_HOST, _MONGO_PORT, _MONGO_DB, _MONGO_COLLECTION, _MONGO_SERVICE = parse_dotenv()

MONGO_HOST = _MONGO_HOST
MONGO_PORT = _MONGO_PORT
MONGO_DB = _MONGO_DB
MONGO_COLLECTION = _MONGO_COLLECTION
MONGO_SERVICE = _MONGO_SERVICE
