from src.utils.env import parse_dotenv

_PROXY_LOGIN, _PROXY_PASSWORD, _MONGO_TOKEN_DB, _MONGO_TOKEN_PORT, _SITE_NAME, _COUNT_ACTIONS_UNITL_EXIT = parse_dotenv(
)

PROXY_LOGIN = _PROXY_LOGIN
PROXY_PASSWORD = _PROXY_PASSWORD

MONGO_TOKEN_DB = _MONGO_TOKEN_DB
MONGO_TOKEN_PORT = _MONGO_TOKEN_PORT

SITE_NAME = _SITE_NAME

COUNT_ACTIONS_UNITL_EXIT = _COUNT_ACTIONS_UNITL_EXIT