cases = {
    "+79208313140": [
        {
            "url_profile": "https://ok.ru/profile/360296191568",
            "name": "Владимир Ковынев",
            "first_name": "Владимир",
            "last_name": "Ковынев",
            "shortname": None,
            "bio": "1991  403 центральный военный завод по ремонту средств связи",
            "age": 50,
            "birthday": "1973-04-15",
            "birthday_set": "Да",
            "gender": "Мужской",
            "locale": "ru",
            "relationship": None,
            "location_city": "Брянск",
            "location_country": None,
            "location_of_birth_city": None,
            "location_of_birth_country": None,
            "registered_date": "2010-04-20 21:48:04",
            "last_online": "2023-10-13 22:21:50",
            "counter_applications": 2,
            "counter_friends": 73,
            "counter_groups": 8,
            "counter_photo_albums": 3,
            "counter_photos_personal": 3,
            "counter_products": 0,
            "counter_subscribers": 25,
            "premium": "Нет",
            "private": "Нет",
            "blocked": "Нет",
            "is_merchant": "Нет",
            "is_new_user": "Нет",
            "invited_by_friend": "Нет",
            "access_level_age": "ALL",
            "access_level_feed": "ALL",
            "access_level_now": "ALL",
            "access_level_video": "ALL",
            "accessible": "Да",
            "allows_anonym_access": "Да",
            "allows_messaging_only_for_friends": "Нет",
            "avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqp37btZnMO0N7pBiM9ZBG5Mz3Mcm4jVVlovXxzt9TtYDo",
            "list__photos": [
                "https://i.mycdn.me/i?r=AzHhPDWh9gzRnVlEH0jk1oHYX3KoKqKL_YR3yUDgU5h1Bsm748BkRMZYZEML7f8a-TA",
                "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqp2zQQRSIb9h6cOX5-5eSL-VEqGxiVsCBhjfGe1NbWk0w",
                "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqp2zQQRSIb9h6cOX5-5eSL-T3Mcm4jVVlovXxzt9TtYDo",
            ],
            "Type": "profile",
        },
        {
            "communities_type": "Служба",
            "communities_name": "63791 - 50 ОБСВГ!!",
            "communities_abbreviation": None,
            "communities_country": "Россия",
            "communities_city": "Москва",
            "communities_address": "рябиновая-42",
            "communities_year_from": 1991,
            "communities_year_to": 1993,
            "Type": "period",
        },
        {
            "communities_type": "Служба",
            "communities_name": "63791  ОБСВГ",
            "communities_abbreviation": None,
            "communities_country": "Россия",
            "communities_city": "Москва",
            "communities_address": "ул. Рябиновая-63",
            "communities_year_from": 1991,
            "communities_year_to": 1993,
            "Type": "period",
        },
        {
            "communities_type": "Служба",
            "communities_name": "63791",
            "communities_abbreviation": None,
            "communities_country": "Россия",
            "communities_city": "Москва",
            "communities_address": "Рябиновая 42 А",
            "communities_year_from": 1991,
            "communities_year_to": 1993,
            "Type": "period",
        },
        {
            "communities_type": "Служба",
            "communities_name": "50 отдельный батальон сопровождения воинских грузов",
            "communities_abbreviation": None,
            "communities_country": "Россия",
            "communities_city": "Москва",
            "communities_address": "москва,улица РЯБИНОВАЯ 42-а.",
            "communities_year_from": 1991,
            "communities_year_to": 1993,
            "Type": "period",
        },
        {
            "communities_type": "Школа",
            "communities_name": "3 школа",
            "communities_abbreviation": None,
            "communities_country": "Россия",
            "communities_city": "Брянск",
            "communities_address": None,
            "communities_year_from": 1980,
            "communities_year_to": 1990,
            "Type": "period",
        },
        {
            "groups_name": "63791 50 ОБСВГ!!!",
            "groups_description": "ГРУППА ДЛЯ ЛЮДЕЙ ИЗ ОБСВГ",
            "groups_created": "2008-05-20 20:07:09.460000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sPUpkBJK5ocw7toFT0IEygg",
            "groups_members": 353,
            "groups_private": "Да",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "ОБСВГ - 50 ЧМО",
            "groups_description": "Армия",
            "groups_created": "2009-02-08 20:29:03.093000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sE8sb_KUTNpVoLTOsgD_4c0",
            "groups_members": 331,
            "groups_private": "Да",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "БСВГ",
            "groups_description": "Чумари всех стран - объединяйтесь!!!!",
            "groups_created": "2009-05-06 18:38:28.300000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sLpZJ11viYH27xeTLxKX52A",
            "groups_members": 572,
            "groups_private": "Да",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "Кино-Фильмы-Гифы  2020",
            "groups_description": None,
            "groups_created": "2014-05-04 14:31:19.673000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sNqptmIXr0cwxpXPORKnrqA",
            "groups_members": 666656,
            "groups_private": "Нет",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": 'Социальная сеть "Вконтакте"',
            "groups_description": "Размещение рекламы строго через администратора группы, в ином случае удаление рекламы и черный список.",
            "groups_created": "2009-03-01 09:20:13.147000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sEXCdDhUnT7vyBBxDl_7dt8",
            "groups_members": 30073,
            "groups_private": "Нет",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "Геология",
            "groups_description": "Истории о практиках, вспомним минералы и просто весело проведем время в компании нас геологов.",
            "groups_created": "2008-06-04 19:36:24.510000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sNOvJQZb9BozD87tp7n3iZo",
            "groups_members": 15236,
            "groups_private": "Да",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "да здравствуют ковыневы!",
            "groups_description": "группа,которая объединяет всех ковыневых",
            "groups_created": "2008-07-04 16:11:34.540000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sM08CxjlKUN2LnmcpKvIZvs",
            "groups_members": 188,
            "groups_private": "Нет",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "groups_name": "1.Минералы и горные породы. 2.Палеонтология",
            "groups_description": "Все , кто увлекается , изучает , знает минералы и горные породы, интересуется живым прошлым Земли, присоединяйтесь!!!",
            "groups_created": "2009-10-22 20:57:37.770000",
            "groups_avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpZFkLVZ3OJuW-gLrq6NX-sGrEGcWNicYiOG8NUOQvND4",
            "groups_members": 6841,
            "groups_private": "Нет",
            "groups_premium": "Нет",
            "groups_category": "CUSTOM",
            "Type": "group",
        },
        {
            "url_profile": "https://ok.ru/profile/330129684653",
            "name": "Лариса Лазуто Петухина",
            "shortname": None,
            "avatar": "https://i.mycdn.me/i?r=AzFZjk43g7nXaldx-NPOkCkHkflVhftbt9rM5StVTggeoodLr6pnO89RZhIKMlTJ7yQ",
            "gender": "Женский",
            "relationships": "Сестра",
            "Type": "relative",
        },
        {
            "url_profile": "https://ok.ru/profile/463013275324",
            "name": "Юра Ковынев",
            "shortname": "yura.kovynev",
            "avatar": "https://i.mycdn.me/i?r=AzG3kTyUv2_AbBh756SPDYqpFrSHL_Th1HX1jJXOtVhr0vQSyyE6HPhML5tCTCdg2Vo",
            "gender": "Мужской",
            "relationships": "Родственник",
            "Type": "relative",
        },
    ],
    "kovinevmv@gmail.com": [
        {
            "url_profile": "https://ok.ru/profile/582066751081",
            "name": "Максим Ковынев",
            "first_name": "Максим",
            "last_name": "Ковынев",
            "shortname": None,
            "bio": None,
            "age": 25,
            "birthday": "1998-08-31",
            "birthday_set": "Да",
            "gender": "Мужской",
            "locale": "ru",
            "relationship": None,
            "location_city": "",
            "location_country": None,
            "location_of_birth_city": None,
            "location_of_birth_country": None,
            "registered_date": "2022-05-23 18:20:31",
            "last_online": "2022-12-05 19:46:35",
            "counter_applications": 0,
            "counter_friends": 0,
            "counter_groups": 0,
            "counter_photo_albums": 0,
            "counter_photos_personal": 0,
            "counter_products": 0,
            "counter_subscribers": 0,
            "premium": "Нет",
            "private": "Нет",
            "blocked": "Нет",
            "is_merchant": "Нет",
            "is_new_user": "Нет",
            "invited_by_friend": "Нет",
            "access_level_age": "ALL",
            "access_level_feed": "ALL",
            "access_level_now": "ALL",
            "access_level_video": "ALL",
            "accessible": "Да",
            "allows_anonym_access": "Да",
            "allows_messaging_only_for_friends": "Нет",
            "avatar": None,
            "list__photos": [],
            "Type": "profile",
        }
    ],
}
