from src.utils.env import parse_dotenv

_SELENIUM_BROWSER_DRIVER_PATH, _SMS_ACTIVATE_TOKEN = parse_dotenv()

SELENIUM_BROWSER_DRIVER_PATH = _SELENIUM_BROWSER_DRIVER_PATH
SMS_ACTIVATE_TOKEN = _SMS_ACTIVATE_TOKEN
