// Code generated by xgen. DO NOT EDIT.

package schema

// PersonReq ...
type PersonReq struct {
	First          string `xml:"first,omitempty" json:"first,omitempty"`
	Middle         string `xml:"middle,omitempty" json:"middle,omitempty"`
	Paternal       string `xml:"paternal,omitempty" json:"paternal,omitempty"`
	BirthDt        string `xml:"birthDt,omitempty" json:"birthdt,omitempty"`
	Passportseries string `xml:"passport_series,omitempty" json:"passportseries,omitempty"`
	Passportnumber string `xml:"passport_number,omitempty" json:"passportnumber,omitempty"`
	IssueDate      string `xml:"issueDate,omitempty" json:"issuedate,omitempty"`
	IssueAuthority string `xml:"issueAuthority,omitempty" json:"issueauthority,omitempty"`
	Inn            string `xml:"inn,omitempty" json:"inn,omitempty"`
	Snils          string `xml:"snils,omitempty" json:"snils,omitempty"`
	Drivernumber   string `xml:"driver_number,omitempty" json:"drivernumber,omitempty"`
	Driverdate     string `xml:"driver_date,omitempty" json:"driverdate,omitempty"`
	Regionid       int    `xml:"region_id,omitempty" json:"regionid,omitempty"`
}

// PhoneReq ...
type PhoneReq struct {
	Phone string `xml:"phone,omitempty" json:"phone,omitempty"`
}

// EmailReq ...
type EmailReq struct {
	Email string `xml:"email,omitempty" json:"email,omitempty"`
}

// IPReq ...
type IPReq struct {
	Ip string `xml:"ip,omitempty" json:"ip,omitempty"`
}

// SkypeReq ...
type SkypeReq struct {
	Skype string `xml:"skype,omitempty" json:"skype,omitempty"`
}

// TelegramReq ...
type TelegramReq struct {
	Skype string `xml:"skype,omitempty" json:"skype,omitempty"`
}

// NickReq ...
type NickReq struct {
	Nick string `xml:"nick,omitempty" json:"nick,omitempty"`
}

// URLReq ...
type URLReq struct {
	Url string `xml:"url,omitempty" json:"url,omitempty"`
}

// CarReq ...
type CarReq struct {
	Vin     string `xml:"vin,omitempty" json:"vin,omitempty"`
	Bodynum string `xml:"bodynum,omitempty" json:"bodynum,omitempty"`
	Chassis string `xml:"chassis,omitempty" json:"chassis,omitempty"`
	Regnum  string `xml:"regnum,omitempty" json:"regnum,omitempty"`
	Ctc     string `xml:"ctc,omitempty" json:"ctc,omitempty"`
	Pts     string `xml:"pts,omitempty" json:"pts,omitempty"`
}

// OrgReq ...
type OrgReq struct {
	Inn      string `xml:"inn,omitempty" json:"inn,omitempty"`
	Ogrn     string `xml:"ogrn,omitempty" json:"ogrn,omitempty"`
	Name     string `xml:"name,omitempty" json:"name,omitempty"`
	Address  string `xml:"address,omitempty" json:"address,omitempty"`
	Regionid int    `xml:"region_id,omitempty" json:"regionid,omitempty"`
	Bik      int    `xml:"bik,omitempty" json:"bik,omitempty"`
}

// Request ...
type Request struct {
	UserIP      string         `xml:"UserIP,omitempty" json:"userip,omitempty"`
	UserID      string         `xml:"UserID,omitempty" json:"userid,omitempty"`
	Password    string         `xml:"Password,omitempty" json:"password,omitempty"`
	RequestId   string         `xml:"requestId,omitempty" json:"requestid,omitempty"`
	RequestType string         `xml:"requestType,omitempty" json:"requesttype,omitempty"`
	Sources     string         `xml:"sources,omitempty" json:"sources,omitempty"`
	Rules       string         `xml:"rules,omitempty" json:"rules,omitempty"`
	Recursive   int            `xml:"recursive,omitempty" json:"recursive,omitempty"`
	Async       int            `xml:"async,omitempty" json:"async,omitempty"`
	Timeout     int            `xml:"timeout,omitempty" json:"timeout,omitempty"`
	PersonReq   *PersonReq     `xml:"PersonReq,omitempty" json:"personreq,omitempty"`
	PhoneReq    []*PhoneReq    `xml:"PhoneReq,omitempty" json:"phonereq,omitempty"`
	EmailReq    []*EmailReq    `xml:"EmailReq,omitempty" json:"emailreq,omitempty"`
	IPReq       []*IPReq       `xml:"IPReq,omitempty" json:"ipreq,omitempty"`
	SkypeReq    []*SkypeReq    `xml:"SkypeReq,omitempty" json:"skypereq,omitempty"`
	TelegramReq []*TelegramReq `xml:"TelegramReq,omitempty" json:"telegramreq,omitempty"`
	NickReq     []*NickReq     `xml:"NickReq,omitempty" json:"nickreq,omitempty"`
	URLReq      []*URLReq      `xml:"URLReq,omitempty" json:"urlreq,omitempty"`
	CarReq      *CarReq        `xml:"CarReq,omitempty" json:"carreq,omitempty"`
	OrgReq      *OrgReq        `xml:"OrgReq,omitempty" json:"orgreq,omitempty"`
}

// Async is БИК банка
type Async int
