FROM git.i-sphere.local/isphere-images/python:3.11-slim-buster
ARG GIT_HTTP_URL_WITH_CREDENTIALS
WORKDIR /app
COPY projects/worker .
COPY lib ./lib
RUN pip install --no-cache-dir pipenv==2022.1.8 && \
    pipenv install --skip-lock --system --deploy && \
    pip uninstall pipenv -y
CMD [ "python", "start.py" ]
